from .defaults import BLOB_VARS, BUFFER_VARS, DEFAULT_VARS
from .utils import get_env_dir


def main() -> None:

    env_dir = get_env_dir()

    # create file to write to
    with open(env_dir / ".env", "w") as f:

        # Set a header
        f.write("# This file is autogenerated via\n")
        f.write("# `python rfinder.environment.generate`\n")
        f.write("# To override these values, copy this file to .env.local\n")
        f.write("# and make your overrides there\n")
        f.write("\n")

        for key, val in DEFAULT_VARS.items():
            f.write("{}={}\n".format(key, val))
        f.write("\n")

        f.write("# TRAINING ON BLOBS\n")
        for key, val in BLOB_VARS.items():
            f.write("{}={}\n".format(key, val))
        f.write("\n")

        f.write("# RUNNING A BUFFER\n")
        for key, val in BUFFER_VARS.items():
            f.write("{}={}\n".format(key, val))
        f.write("\n")


if __name__ == "__main__":
    main()
