from .defaults import DEFAULT_VARS
from .utils import get_env_dir


def main() -> None:

    env_dir = get_env_dir()

    # create file to write to
    with open(env_dir / ".env", "w") as f:

        # Set a header
        f.write("# This file is autogenerated via")
        f.write("# `python rfind_web.environment.generate`")
        f.write("# To override these values, copy this file to .env.local")
        f.write("# and make your overrides there")
        f.write("\n")

        for key, val in DEFAULT_VARS.items():
            f.write("{}={}\n".format(key, val))
        f.write("\n")


if __name__ == "__main__":
    main()
